# Generated by Django 5.2.3 on 2025-07-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='biblioteca.autor'),
        ),
    ]
